---
build_from:
  aarch64: ghcr.io/hassio-addons/base:14.0.3
  amd64: ghcr.io/hassio-addons/base:14.0.3
  armhf: ghcr.io/hassio-addons/base:14.0.3
  armv7: ghcr.io/hassio-addons/base:14.0.3
  i386: ghcr.io/hassio-addons/base:14.0.3
codenotary:
  base_image: soufian.daoudi2@gmail.com
  signer: soufian.daoudi2@gmail.com
