name: "PyServer"
description: "PyServer, My first real add-on with devcontainers 2!"
version: dev
slug: "pyserver"
url: https://github.com/sdaoudi/home-assistant-addon
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  8000/tcp: 8000
image: "ghcr.io/sdaoudi/{arch}-pyserver"
