name: "PyServer"
description: "PyServer, My first real add-on!"
version: "1.0.0"
slug: "pyserver"
url: https://github.com/sdaoudi/home-assistant-addon
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8000/tcp: 8000
image: ghcr.io/sdaoudi/pyserver:1.0.0